/*
 * This file is part of KubeSphere Console.
 * Copyright (C) 2019 The KubeSphere Console Authors.
 *
 * KubeSphere Console is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * KubeSphere Console is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with KubeSphere Console.  If not, see <https://www.gnu.org/licenses/>.
 */

module.exports = {
  abortPipeline: '파이프라인 중단',
  'Absolute duration': '절대 지속 시간',
  'Add another credential': '다른 자격 증명 추가',
  'Add conditions': '조건 추가',
  'Add nesting conditions': '중첩 조건 추가',
  'Add nesting steps': '중첩 단계 추가',
  'Add Parallel Stage': '병렬 단계 추가',
  'Add Step': '단계 추가',
  archiveArtifacts: '아티팩트 보관',
  'Are you sure to close this pipeline Editor ?': '이 파이프라인 편집기를 닫을까요?',
  artifacts: '아티팩트',
  'Authentication Token': '인증 토큰',
  'Automatically generated by GitHub': 'GitHub에서 자동으로 생성됨',
  bcc: 'bcc',
  BEHAVIORAL_STRATEGY: '행동 전략',
  blocker: '블로커',
  BLOCKER: '블로커',
  NOTICE: '알림',
  Branches: '브랜치',
  'branch success': '브랜치 성공',
  '@somebody to help review': '@somebody 검토를 도와주세요',
  'Send messages by email': '이메일로 메시지 보내기',
  'Send messages in the build': '빌드 중에 메시지 보내기',
  'Change Current Directory': '현재 디렉토리 변경',
  'Chinese is not allowed in the pipeline configuration': '중국어는 파이프라인 구성에서 허용되지 않습니다',
  'Clean when aborted': '중단시 정리',
  'Clean Workspace': '작업 공간 정리',
  'Code Quality Check': '코드 품질 확인',
  COMMIT_ID: '커밋 ID',
  'Config File Path': '구성 파일 경로',
  'config name': '구성 이름',
  configs: '구성',
  'Configuration error': '구성 오류',
  container: '컨테이너',
  Continue: '계속',
  'credential Id': '자격 증명 ID',
  'Credential Id': '자격 증명 ID',
  credentialsId: '자격 증명 ID',
  critical: '중요',
  'Current branch name must match the input value': '현재 브랜치 이름은 입력 값과 일치해야 합니다',
  'defaultValue -1 means not to discard': 'defaultValue -1은 폐기하지 않는다는 의미입니다',
  'Delete all resources of the deployment file': '배포 파일의 모든 리소스 삭제',
  'Deploy resources to the Kubernetes cluster': 'Kubernetes 클러스터에 리소스 배포',
  "Didn't pass": '실패',
  dir: '디렉토리',
  Discard: '폐기',
  'Discover branches from repository': '저장소에서 브랜치 찾기',
  DISCOVER_PR_FROM_FORKS: 'Fork로부터 PR 찾기',
  DISCOVER_PR_FROM_ORIGIN: 'Origin으로부터 PR 찾기',
  'Discover pull requests from forks': 'Fork로부터 pull requests 찾기',
  'Discover pull requests from origin': 'Origin으로부터 pull requests 찾기',
  'Docker Container Registry Credentials': 'Docker 컨테이너 레지스트리 자격 증명',
  'Docker Registry URL': 'Docker 레지스트리 URL',
  dockerCredentials: '도커 자격 증명',
  'Drag and drop tasks to sort': '드래그 앤 드롭으로 작업 정렬',
  Duration: '기간',
  echo: 'echo',
  'Edit Config': '구성 편집',
  'Edit Credential': '자격 증명 편집',
  'Enable Variable Substitution in Config': '구성에서 변수 대체 활성화',
  enableConfigSubstitution: '구성 변수 대체 활성화',
  'Enter an expression': '식을 입력하세요',
  'Environment name': '환경 이름',
  'Executes the code inside the block with a determined time out limit.':
  '시간 제한이 있는 블록 내 코드 실행',
  expression: '식',
  Failure: '실패',
  'For accessing GitHub': 'GitHub에 액세스하기 위해',
  'get token': '토큰 가져오기',
  info: '정보',
  input: '입력',
  'Inspection results do not affect subsequent tasks': '검사 결과는 후속 작업에 영향을 미치지 않습니다',
  'instance failed to match at least one schema': '인스턴스가 적어도 하나의 스키마와 일치하지 않습니다',
  'Internal nested conditions only need to satisfy one': '내부 중첩 조건은 하나만 충족하면 됩니다',
  'Internal nesting conditions must be matched': '내부 중첩 조건이 일치해야 합니다',
  'Jenkinsfile syntax error, message': 'Jenkinsfile 구문 오류, 메시지',
  'key File Variable': '키 파일 변수',
  keyFileVariable: '키 파일 변수',
  'Kubeconfig Variable': 'Kubeconfig 변수',
  'Kubernetes Namespace for Secret': '시크릿 Kubernetes 네임스페이스',
  'Kubernetes Secrets': 'Kubernetes Secrets',
  Line: '라인',
  'Load credentials into environment variables': '자격 증명을 환경 변수로 로드',
  'Load the sonarqube configuration provided by Jenkins into the Pipeline.':
  'Jenkins에서 제공하는 sonarqube 구성을 Pipeline에 로드합니다.',
  mail: '메일',
  major: '주요',
  minor: '부',
  "Missing one or more required properties: 'name'": "하나 이상의 필수 속성 누락: '이름'",
  'Negative prefix': '부정적 접두사',
  NO_BRANCH_FOUND_TIP: '브랜치를 찾을 수 없습니다.',
  'No need': '필요 없음',

  Normal: '일반',
  'Not Build': '빌드하지 않음',
  'Not fail build': '빌드 실패하지 않음',

  'not support edit nested stage': '중첩 스테이지 편집 지원하지 않음',

  'passphrase Variable': 'passphrase 변수',
  passphraseVariable: 'passphrase 변수',
  'Password Variable': '비밀번호 변수',
  passwordVariable: '비밀번호 변수',

  PIPELINE_LOW: '파이프라인',

  'Pipeline Configuration': '파이프라인 구성',

  'Pipeline List': '파이프라인 목록',

  'pipeline syntax error': '파이프라인 구문 오류',
  'Please add at least one step.': '적어도 한 단계를 추가하십시오.',
  'Please input images name': '이미지 이름을 입력하십시오.',

  'Please input the credential name.': '자격 증명 이름을 입력하십시오.',

  'Press enter for the next': '다음을 위해 엔터를 누르세요',
  'Print message': '메시지 출력',

  'Pull code by Git': 'Git으로 코드를 가져오기',
  'Pull code by SVN': 'SVN으로 코드를 가져오기',

  Queue: '대기열',

  Recipient: '수신자',

  'Registry Credentials': '레지스트리 자격 증명',
  remote: '원격',
  'Run Pipeline': '파이프라인 실행',
  'Save Artifact': '아티팩트 저장',

  'Repo Scanned Successfully': '저장소 검색 성공',

  WEBHOOK_PUSH: '웹훅 푸시',
  secretName: '비밀 이름',
  secretNamespace: '비밀 네임스페이스',

  SELECT_THIS_REPOSITORY: '이 저장소 선택',
  Sender: '보낸 사람',
  sh: 'sh',
  'Shell commands can be executed in the container':
  '컨테이너에서 셸 명령을 실행할 수 있습니다',
  'Show Advanced Settings': '고급 설정 보기',

  'show yaml editor': 'YAML 편집기 보기',

  'sonar is the default config name.': 'snoar가 기본 구성 이름입니다.',
  "Sorry, you don't have the permission to do this.":
  '죄송합니다. 이 작업을 수행할 권한이 없습니다.',
  'Specify a container to add nested tasks to execute inside the container':
  '컨테이너 내에서 실행할 중첩 작업을 추가하려면 컨테이너를 지정하십시오',
  'Start the follow-up task after the inspection': '검사 후 후속 작업 시작',
  'Started By': '시작한 사용자',

  Subject: '제목',
  submitter: '제출자',
  submitterParameter: '제출자 매개 변수',

  'Text Variable': '텍스트 변수',
  'The conditions required to implement the current phase (optional).': '현재 단계를 실행하는 데 필요한 조건 (선택 사항)',
  'The environment variable entered before running the pipeline is match the current value.': '파이프라인을 실행하기 전에 입력한 환경 변수가 현재 값과 일치합니다.',
  'The label on which to run the Pipeline or individual stage': '파이프라인 또는 개별 스테이지를 실행할 라벨',
  'This name has been used.': '현재 사용 중인 이름입니다.',
  'Time Used': '사용 시간',
  Timeout: '시간 초과',
  timeout: '시간 초과',
  'Timeout after no activity in logs for this block': '로그에서 활동이 없을 때 블록 시간 초과',
  timer: '타이머',
  TRIGGER_REMOTE_BUILD: '원격 빌드 트리거 (예: 스크립트 사용)',
  Unnamed: '이름 없음',
  'Use the following URL to remotely triggerworkbench the build': '다음 URL을 사용하여 원격으로 빌드를 트리거합니다.',
  'User types that can trigger builds': '빌드를 트리거할 수 있는 사용자 유형',
  'username or group name, multiple values ​​used, separated': '사용자 이름 또는 그룹 이름, 여러 값 사용, 구분',
  'Username Variable': '사용자 이름 변수',
  usernameVariable: '사용자 이름 변수',
  waitForQualityGate: '품질 게이트 대기',
  Webhook: 'Webhook',
  withCredentials: '자격 증명 사용',
  withSonarQubeEnv: 'SonarQube 환경 사용',
  'Wrong Token': '잘못된 토큰',
  'You can execute shell commands or windows batch commands in the build.': '빌드에서 셸 명령 또는 윈도우 배치 명령을 실행할 수 있습니다.',
  PIPELINE_DESC: '파이프라인은 지속적인 통합 및 지속적인 전달을 달성하기 위해 조합할 수 있는 확장 가능한 도구 세트입니다. 이 페이지에서 파이프라인을 생성하고 관리할 수 있습니다.',
  username_password: '사용자 이름 및 암호',
  login_Plateform: '로그인 플랫폼',
  CREDENTIALS_DESC: '자격 증명은 사용자 이름 및 암호, SSH 키 및 토큰과 같은 일부 민감한 데이터를 포함하는 객체입니다. 파이프라인 실행 중 코드를 끌어오기, 이미지를 푸시/풀링, SSH 스크립트를 실행하는 데 인증을 제공하는 데 사용됩니다.',
  AUTHENTICATION_TOKEN_TIP: `사전에 정의된 URL에 액세스하여 빌드를 트리거해야하는 경우 이 옵션을 활성화하십시오. 이 기능의 일반적인 사용은 소스 코드 관리 시스템의 후크 스크립트를 통해 트리거하는 것입니다. 권한 토큰을 문자열 형태로 제공해야합니다. 권한 토큰을 가진 사람만 원격 빌드를 트리거 할 수 있습니다.`,
  CRON_TIP: `이 필드는 cron 구문을 따릅니다.
    구체적으로 각 줄에는 탭이나 공백으로 구분된 5 개의 필드가 포함됩니다.
    분 : 시간의 처음 몇 분 (0-59)
    시간 : 하루의 처음 몇 시간 (0-23)
    월의 일수 : 월의 처음 몇 일 (1-31)
    월 : 첫 번째 몇 일 (0-12), 첫 번째 몇 주 (0-12), 0과 7은 일요일입니다.`,

  PIPELINES_BASEINFO_DESC:
    '파이프라인의 기본 정보를 입력하십시오.',
  PIPELINE_ADVANCE_SETTINGS_DESC:
    '파이프라인에 대한 복잡한 동작 정책을 구성하십시오. (선택 사항)',
  CREDENTIALS_CREATE_DESC: 'DevOps 프로젝트를 위한 자격 증명을 생성하십시오.',
  CHECKOUT_DESC: '코드 끌어오기; 주로 svn과 같은 git이 아닌 코드를 끌어올 때 사용됨.',
  PRIVATE_IMAGE_DESC: `개인 이미지 저장소에서 배포하려면 먼저 미러 이미지 저장소를 생성한 다음 이미지를 끌어와야합니다. `,

  AUTHENTICATION_TOKEN_DESC: `빌드를 원격으로 트리거하기 위해 다음 URL을 사용하십시오: JENKINS_URL/job/JOB_NAME/build?token=TOKEN_NAME 또는/buildWithParameters?token=TOKEN_NAME &cause=reason을 추가하여 빌드 이유를 기록하는 데 사용될 텍스트를 제공할 수 있습니다.`,

  PIPELINE_NO_CONFIG:
    '현재 파이프라인에서 관련된 구성 파일을 찾을 수 없습니다.',


  EDIT_CREDENTIAL_DESC:
    '다음 양식은 원래 자격 증명 정보를 표시하지 않습니다. 새 입력으로 기존 정보가 덮어 씌워집니다.',
  pipeline_conditions: '조건',

  CODE_SMELL: '코드 스멜',
  BUG: '버그',

  VULNERABILITY: '취약점',
  SECURITY_HOTSPOT: '보안 핫스팟',
  PIPELINE_CREATE_DESC:
  "파이프라인의 작업 실행은 초기화가 완료된 후 시작됩니다.",
  PIPELINE_QUEUED_DESC:
  "에이전트가 시작되어 파이프라인이 실행될 때까지 기다려야 합니다. (에이전트가 오랜 시간동안 시작되지 않았다면, 에이전트 구성 및 클러스터 리소스를 확인해주세요.)",
  waitForQualityGate_desc:
  "코드 품질 검사 기준은 SonarQube의 품질 게이트에서 파생됩니다. 기준을 사용자 정의해야 하는 경우 SonarQube 설정으로 이동하십시오.",
  REVIEW_DESC:
  "파이프라인이 여기에서 실행될 때, 이 작업은 일시 중지되며, 검토 후 계속 진행할지 종료할지 선택할 수 있습니다.",
  INPUT_DESC:
  "파이프라인이 여기에서 실행될 때, 작업이 일시 중지되며, 작성자와 @somebody는 파이프라인을 계속 진행할지 종료할지 선택할 수 있습니다.",

  LoadPrevData_Desc:
  "이 파이프라인이 마지막으로 성공적으로 편집되지 않았음을 감지했습니다. 마지막 데이터를 로드하여 편집을 계속할까요?",
  withSonarQubeEnv_DESC:
  "코드에서 잠재적 또는 명백한 오류를 빠르게 찾아보세요",
  waitForQualityGate_DESC: "코드 분석을 수행한 후 실행됩니다",
  script_DESC: "그루비 스크립트를 실행합니다",
  pipeline_owner:
  "DevOps 프로젝트의 소유자는 프로젝트의 최고 권한으로 모든 작업을 수행할 수 있습니다.",
  pipeline_maintainer:
  "DevOps 프로젝트의 유지 관리자는 자격 증명 및 파이프라인 구성을 수행할 수 있습니다.",
  pipeline_developer:
  "DevOps 프로젝트의 개발자는 파이프라인을 트리거하고 볼 수 있습니다.",
  pipeline_reporter:
  "DevOps 프로젝트의 관찰자는 프로젝트 리소스만 볼 수 있습니다.",

  PATTERN_PIPELINE_NAME_VALID_NAME_TIP:
  "유효하지 않은 이름 (대소문자, 숫자, '_' 및 '-'를 지원합니다.)",
  GET_GITHUB_TOKEN_DESC: `GitHub에 접근하여
  <a
    class="float-right"
    href="https://github.com/settings/tokens/new?scopes=repo,read:user,user:email,write:repo_hook"
    target="_blank"
  >
    토큰 가져오기
  </a>`,

  PIPELINES_FOOTER_SEE_MORE: '자세한 내용은 브랜치 세부 정보 페이지에서 확인하세요.',

  JENKINS_LINS_ERROR: '{line}번째 줄에 구문 오류가 있습니다.', // Concatenated

  'Invalid credential ID': '잘못된 자격 증명 ID입니다.',

  'Batch Run Fail': '일괄 실행에 실패했습니다.',
  'Run Start': '실행 시작',

  'Choose a Pipeline Template': '파이프라인 템플릿 선택',

  // Pipeline Creation Page
  DEVOPS_PROJECT_DESC: 'DevOps 프로젝트는 자원을 그룹화하고 다른 사용자의 자원 관리 권한을 제어하는 데 사용됩니다.',
}
